from __future__ import annotations

from soilflow_pflotran_modules.input_contract import pf_float


def _test_output_block(snapshot_period_line: str = "  PERIODIC TIMESTEP 1") -> list[str]:
    return [
        "OUTPUT",
        "  TIME_UNITS day",
        "  SNAPSHOT_FILE",
        "    FORMAT TECPLOT POINT",
        snapshot_period_line,
        "    VARIABLES",
        "      LIQUID_PRESSURE",
        "      LIQUID_SATURATION",
        "      LIQUID_HEAD",
        "      LIQUID_RELATIVE_PERMEABILITY",
        "      POROSITY",
        "      PERMEABILITY",
        "      MATERIAL_ID",
        "    /",
        "  /",
        "  MASS_BALANCE_FILE",
        "    PERIODIC TIMESTEP 1",
        "  /",
        "  CONSERVATION_FILE",
        "    PERIODIC TIMESTEP 1",
        "  /",
        "  VELOCITY_AT_CENTER",
        "  SCREEN PERIODIC 1",
        "/",
    ]


def generate_richards_profile_input(test_name: str) -> str:
    length_x_m = 1.0
    length_y_m = 1.0
    column_height_m = 1.2
    nx, ny, nz = 1, 1, 96
    dx = length_x_m / nx
    dy = length_y_m / ny
    dz = column_height_m / nz
    porosity = 0.43
    residual_saturation = 0.10465116279069768
    rho = 997.0
    gravity = 9.80665
    mu = 0.00089
    ksat_m_s = 5.0e-6
    intrinsic_perm_m2 = ksat_m_s * mu / (rho * gravity)
    alpha_1_m = 3.6
    n = 1.56
    m = 1.0 - 1.0 / n
    atmospheric_pressure_pa = 101325.0

    if test_name == "green_ampt_infiltration":
        final_time_days = 0.5
        max_dt_days = 0.0025
        top_flux_m_s = 1.2e-6
        initial_head_m = -1.4
        title = "Green-Ampt numerical Richards profile"
    elif test_name == "philip_infiltration":
        final_time_days = 0.25
        max_dt_days = 0.00125
        top_flux_m_s = 8.0e-7
        initial_head_m = -1.0
        title = "Philip numerical Richards profile"
    else:
        final_time_days = 0.5
        max_dt_days = 0.0025
        top_flux_m_s = 0.0
        initial_head_m = -1.0
        title = "Richards MMS profile carrier"

    initial_pressure_pa = atmospheric_pressure_pa + rho * gravity * initial_head_m
    snapshot_step = max(1, int(round(0.025 / max_dt_days)))
    lines = [
        f"# Generated by soilflow_pflotran.py --mode _test --test {test_name}",
        f"# {title}.",
        "# Этот deck дает расчетные TECPLOT-профили PFLOTRAN для Richards-связанных",
        "# аналитических benchmark'ов, пока строгая MMS/инфильтрационная метрика",
        "# подключается отдельным этапом.",
        "",
        "SIMULATION",
        "  SIMULATION_TYPE SUBSURFACE",
        "  PROCESS_MODELS",
        "    SUBSURFACE_FLOW flow",
        "      MODE RICHARDS",
        "    /",
        "  /",
        "END",
        "",
        "SUBSURFACE",
        "",
        "GRID",
        "  TYPE structured",
        "  ORIGIN 0.d0 0.d0 0.d0",
        f"  NXYZ {nx} {ny} {nz}",
        "  DXYZ",
        f"    {pf_float(dx)}",
        f"    {pf_float(dy)}",
        f"    {pf_float(dz)}",
        "  /",
        "END",
        "",
        "MATERIAL_PROPERTY soil",
        "  ID 1",
        f"  POROSITY {pf_float(porosity)}",
        "  TORTUOSITY 1.d0",
        "  CHARACTERISTIC_CURVES cc_vg",
        "  PERMEABILITY",
        f"    PERM_X {pf_float(intrinsic_perm_m2)}",
        f"    PERM_Y {pf_float(intrinsic_perm_m2)}",
        f"    PERM_Z {pf_float(intrinsic_perm_m2)}",
        "  /",
        "/",
        "",
        "CHARACTERISTIC_CURVES cc_vg",
        "  SATURATION_FUNCTION VAN_GENUCHTEN",
        f"    LIQUID_RESIDUAL_SATURATION {pf_float(residual_saturation)}",
        f"    M {pf_float(m)}",
        f"    ALPHA {pf_float(alpha_1_m / (rho * gravity))}",
        "  /",
        "  PERMEABILITY_FUNCTION MUALEM_VG_LIQ",
        f"    LIQUID_RESIDUAL_SATURATION {pf_float(residual_saturation)}",
        f"    M {pf_float(m)}",
        "  /",
        "/",
        "",
        *_test_output_block(f"    PERIODIC TIMESTEP {snapshot_step}"),
        "",
        "TIME",
        f"  FINAL_TIME {pf_float(final_time_days)} d",
        f"  MAXIMUM_TIMESTEP_SIZE {pf_float(max_dt_days)} d",
        "/",
        "",
        "REGION all",
        "  COORDINATES",
        "    0.d0 0.d0 0.d0",
        f"    {pf_float(length_x_m)} {pf_float(length_y_m)} {pf_float(column_height_m)}",
        "  /",
        "END",
        "",
        "REGION top",
        "  COORDINATES",
        f"    0.d0 0.d0 {pf_float(column_height_m)}",
        f"    {pf_float(length_x_m)} {pf_float(length_y_m)} {pf_float(column_height_m)}",
        "  /",
        "  FACE TOP",
        "END",
        "",
        "FLOW_CONDITION initial",
        "  TYPE",
        "    LIQUID_PRESSURE DIRICHLET",
        "  /",
        f"  LIQUID_PRESSURE {pf_float(initial_pressure_pa)}",
        "END",
        "",
    ]
    if top_flux_m_s > 0.0:
        lines += [
            "FLOW_CONDITION top_infiltration",
            "  TYPE",
            "    LIQUID_FLUX NEUMANN",
            "  /",
            "  # Положительный boundary flux направлен внутрь расчетной области.",
            f"  LIQUID_FLUX {pf_float(top_flux_m_s)}",
            "END",
            "",
        ]
    lines += [
        "INITIAL_CONDITION",
        "  FLOW_CONDITION initial",
        "  REGION all",
        "END",
        "",
    ]
    if top_flux_m_s > 0.0:
        lines += [
            "BOUNDARY_CONDITION top_flux_bc",
            "  FLOW_CONDITION top_infiltration",
            "  REGION top",
            "END",
            "",
        ]
    else:
        lines += ["# Границы не назначены: используется no-flow по умолчанию.", ""]
    lines += [
        "STRATA",
        "  REGION all",
        "  MATERIAL soil",
        "END",
        "",
        "END_SUBSURFACE",
        "",
    ]
    return "\n".join(lines)

